language: java
jdk: openjdk8

env:
  - COVERAGE_THRESHOLD=0.3

install:
  - ./gradlew clean jar

script:
  - ./gradlew test
  - ./gradlew jacocoTestReport

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deploy:
  - COVERAGE=$COVERAGE_THRESHOLD ./gradlew test jacocoTestCoverageVerification

deploy:
  provider: script
  script: echo "WIP"
  on:
    all_branches: true
