language: java
jdk:
  - openjdk8
  - openjdk9

script:
  - ./gradlew clean jar

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "UI check"
      jdk: openjdk8
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/ui check
      env:
      - COVERAGE_THRESHOLD=0.05
    - stage: test
      name: "Cart Service check"
      jdk: openjdk8
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/service/cart check
      env:
      - COVERAGE_THRESHOLD=0.14
    - stage: test
      name: "User Service check"
      jdk: openjdk8
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/service/user check
      env:
      - COVERAGE_THRESHOLD=0.0
    - stage: test
      name: "Order repository check"
      jdk: openjdk8
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/order check
      env:
      - COVERAGE_THRESHOLD=0.3
    - stage: test
      name: "Cart repository check"
      jdk: openjdk8
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/cart check
      env:
      - COVERAGE_THRESHOLD=0.0
    - stage: test
      name: "Product repository check"
      jdk: openjdk8
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/product check
      env:
      - COVERAGE_THRESHOLD=0.12
    - stage: test
      name: "User repository check"
      jdk: openjdk8
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/user check
      env:
      - COVERAGE_THRESHOLD=0.3
    - stage: test
      name: "UI check"
      jdk: openjdk9
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/ui check
      env:
      - COVERAGE_THRESHOLD=0.05
    - stage: test
      name: "Cart Service check"
      jdk: openjdk9
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/service/cart check
      env:
      - COVERAGE_THRESHOLD=0.14
    - stage: test
      name: "User Service check"
      jdk: openjdk9
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/service/user check
      env:
      - COVERAGE_THRESHOLD=0.0
    - stage: test
      name: "Order repository check"
      jdk: openjdk9
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/order check
      env:
      - COVERAGE_THRESHOLD=0.3
    - stage: test
      name: "Cart repository check"
      jdk: openjdk9
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/cart check
      env:
      - COVERAGE_THRESHOLD=0.0
    - stage: test
      name: "Product repository check"
      jdk: openjdk9
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/product check
      env:
      - COVERAGE_THRESHOLD=0.12
    - stage: test
      name: "User repository check"
      jdk: openjdk9
      install: skip
      script:
      - COVERAGE=$COVERAGE_THRESHOLD ./gradlew -p ./monolithic/repository/user check
      env:
      - COVERAGE_THRESHOLD=0.3
    - stage: deploy
      name: "Deploy"
      script: skip
      deploy:
        provider: script
        script: echo "WIP"
        on:
          all_branches: true
