language: java
jdk: openjdk8

install:
  - ./gradlew clean jar

script:
  - ./gradlew test
  - ./gradlew jacocoTestReport

after_success:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'

before_deploy:
  - ./gradlew test jacocoTestCoverageVerification

deploy:
  - echo "WIP"
